### ISSUE TITLE
What’s the difference between this and the default extensions?

### ISSUE THREAD

**Issue by BobWs** [standardnotes/plugins#2]
As the title says!

**Comment by kylejbrk** [comment]
Also curious what this repo is

**Comment by moughxyz** [comment]
Plugins in here are no longer offered to new users by default. If you still have the default plugins because you signed up a while ago, we didn't take them away. So for new accounts, the only way to get the "Bold Editor" for example is through this repo.

**Comment by BobWs** [comment]
> Plugins in here are no longer offered to new users by default. If you still have the default plugins because you signed up a while ago, we didn't take them away. So for new accounts, the only way to get the "Bold Editor" for example is through this repo.

Finally after a half year I got the answer!…merry Christmas 🤶 and a happy new year to you all!
